// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// bws_stat
double bws_stat(NumericVector x, NumericVector y);
RcppExport SEXP BWStest_bws_stat(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    __result = Rcpp::wrap(bws_stat(x, y));
    return __result;
END_RCPP
}
// bws_cdf
NumericVector bws_cdf(NumericVector b, int maxj, bool lower_tail);
RcppExport SEXP BWStest_bws_cdf(SEXP bSEXP, SEXP maxjSEXP, SEXP lower_tailSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type maxj(maxjSEXP);
    Rcpp::traits::input_parameter< bool >::type lower_tail(lower_tailSEXP);
    __result = Rcpp::wrap(bws_cdf(b, maxj, lower_tail));
    return __result;
END_RCPP
}
// murakami_stat_parts
NumericVector murakami_stat_parts(IntegerMatrix Parts, int flavor);
RcppExport SEXP BWStest_murakami_stat_parts(SEXP PartsSEXP, SEXP flavorSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerMatrix >::type Parts(PartsSEXP);
    Rcpp::traits::input_parameter< int >::type flavor(flavorSEXP);
    __result = Rcpp::wrap(murakami_stat_parts(Parts, flavor));
    return __result;
END_RCPP
}
// murakami_stat
double murakami_stat(NumericVector x, NumericVector y, int flavor);
RcppExport SEXP BWStest_murakami_stat(SEXP xSEXP, SEXP ySEXP, SEXP flavorSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type flavor(flavorSEXP);
    __result = Rcpp::wrap(murakami_stat(x, y, flavor));
    return __result;
END_RCPP
}
