# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title
#' Perform the Baumgartner-Weiss-Schindler test.
#'
#' @description
#'
#' Compute the Baumgartner-Weiss-Schindler test statistic, the CDF under the
#' null, or perform the hypothesis test.
#'
#' @param x a vector.
#' @param y a vector.
#'
#' @return return the BWS test statistic, \eqn{b}, or the CDF of \eqn{b} under
#' the null.
#'
#' @examples
#'
#'  set.seed(1234)
#'  x <- rnorm(1000)
#'  y <- rnorm(100)
#'  bval <- bws_stat(x,y)
#'
#'  # do it 500 times
#'  set.seed(123)
#'  bvals <- replicate(500, bws_stat(rnorm(50),rnorm(50)))
#'  pvals <- bws_cdf(bvals)
#'  # these should be uniform!
#'  \dontrun{ 
#'    plot(ecdf(pvals)) 
#'  }
#'
#' @template etc
#' @template ref-bws
#' @rdname bws_test
#' @export
bws_stat <- function(x, y) {
    .Call('BWStest_bws_stat', PACKAGE = 'BWStest', x, y)
}

#' @param b a vector of BWS test statistics.
#' @param maxj the maximum value of j to take in the approximate computation
#' of the CDF via equation (2.5). Baumgartner \emph{et. al.} claim that a
#' value of 3 is sufficient.
#' @rdname bws_test
#' @export
bws_cdf <- function(b, maxj = 5L) {
    .Call('BWStest_bws_cdf', PACKAGE = 'BWStest', b, maxj)
}

